### ISSUE TITLE
Conversion to Embers from RF requires half as much RF and sometimes goes negative

### ISSUE THREAD

**Issue by BlueFeuer** [p455w0rd/Embersified#1]
Conversion to Embers from RF requires half as much RF as converting to, and sometimes it generates negative Embers.

Screenshot of it taking half as much embers:
![image](https://user-images.githubusercontent.com/42864665/46211746-ea660580-c2f9-11e8-9531-9e47b50ca98d.png)

Screenshot of output:
![image](https://user-images.githubusercontent.com/42864665/46211776-ff429900-c2f9-11e8-9312-7e7b649809b2.png)

The RF/t display fluctuates but it's always generating twice as much as is pulled.

Sometimes the embers amount goes negative. Always does this on placement, those that work immediately will stay working. When the Ember Multiplier is turned up it seems to do this a lot more often. Screenshot:

![image](https://user-images.githubusercontent.com/42864665/46211893-4af54280-c2fa-11e8-9c43-5152c3a7cfcb.png)

Tested with EnderIO, Embers Rekindled, Embersified and their requirements as the only mods in the pack.

**Comment by p455w0rd** [comment]
Would you be able to join my discord so I can send you a copy that I believe has this fixed? http://p455w0rd.net/discord

**Comment by p455w0rd** [comment]
been over an hour..I will just push updates and hope

**Comment by BlueFeuer** [comment]
Sorry, was away at the time. Got back just in time for the update to be accepted. Tested both bugs and everything seems to be working fine. Thanks.
